import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "mgo-30",
    slug: "mgo-30",
    name: "Manuka Honey MGO 30",
    mgo: 30,
    price: 14,
    size: "250g",
    potency: 1,
    rating: 4,
    tagline: "Your Daily Golden Glow",
    description: "Entry-level Manuka honey for daily use and general wellness. Cold-extracted Australian Manuka honey with high antibacterial properties based on MGO level.",
    benefits: ["Daily Wellness", "Natural Energy", "Sugar Substitute"],
    bestFor: "Daily Use",
    antibacterial: "Low",
    taste: "Mild",
    image: "/assets/products/WhatsApp Image 2026-05-10 at 5.26.08 AM.jpeg",
    color: "#C8A96E",
  },
  {
    id: "mgo-100",
    slug: "mgo-100",
    name: "Manuka Honey MGO 100",
    mgo: 100,
    price: 18,
    size: "250g",
    potency: 2,
    rating: 4,
    tagline: "Active Immune Support",
    description: "Moderate strength Manuka honey suitable for regular health support. Cold-extracted Australian Manuka honey with high antibacterial properties based on MGO level.",
    benefits: ["Digestive Support", "Immunity Boost", "Health Maintenance"],
    bestFor: "Wellness",
    antibacterial: "Moderate",
    taste: "Mild-Med",
    image: "/assets/products/WhatsApp Image 2026-05-10 at 5.26.09 AM.jpeg",
    color: "#C49A2A",
  },
  {
    id: "mgo-263",
    slug: "mgo-263",
    name: "Manuka Honey MGO 263",
    mgo: 263,
    price: 40,
    size: "250g",
    potency: 3,
    rating: 5,
    tagline: "Natural Shield Protection",
    description: "Cold-extracted Australian Manuka honey with high antibacterial properties based on MGO level. Ideal for targeted immunity and natural protection.",
    benefits: ["Strong Immunity", "Oral Health", "Gut Balance"],
    bestFor: "Immunity",
    antibacterial: "High",
    taste: "Medium",
    image: "/assets/products/3.jpeg",
    color: "#D4930A",
  },
  {
    id: "mgo-400",
    slug: "mgo-400",
    name: "Manuka Honey MGO 400",
    mgo: 400,
    price: 70,
    size: "250g",
    potency: 4,
    rating: 5,
    tagline: "Therapeutic Grade Purity",
    description: "Cold-extracted Australian Manuka honey with high antibacterial properties based on MGO level. Therapeutic grade purity for intensive wellness.",
    benefits: ["Wound Healing", "Intensive Gut Health", "Skin Care"],
    bestFor: "Gut/Wound",
    antibacterial: "Very High",
    taste: "Strong",
    image: "/assets/products/4.jpeg",
    color: "#B87800",
  },
  {
    id: "mgo-800",
    slug: "mgo-800",
    name: "Manuka Honey MGO 800",
    mgo: 800,
    price: 160,
    size: "250g",
    potency: 5,
    rating: 5,
    tagline: "Clinical Grade Powerhouse",
    description: "Our most potent, clinical-grade Manuka. Cold-extracted Australian Manuka honey with high antibacterial properties based on MGO level.",
    benefits: ["Clinical Support", "Max Antibacterial", "Premium Recovery"],
    bestFor: "Clinical",
    antibacterial: "Exceptional",
    taste: "Intense",
    image: "/assets/products/3.jpeg", // Reusing 3.jpeg for now as I only have 4 product images
    color: "#9B6500",
  },
];