import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "mgo-30",
    slug: "mgo-30",
    name: "Manuka Honey MGO 30",
    mgo: 30,
    price: 14,
    size: "250g",
    potency: 1,
    tagline: "Your Daily Golden Glow",
    description: "Perfect for daily wellness and natural sweetness. Our MGO 30 provides a mild introduction to the benefits of Australian Manuka.",
    benefits: ["Daily Wellness", "Natural Energy", "Sugar Substitute"],
    bestFor: "Daily Use",
    antibacterial: "Low",
    taste: "Mild",
    image: "/honey-frames/ezgif-frame-004.jpg",
    imageLid: "/honey-frames/ezgif-frame-014.jpg",
    color: "#C8A96E",
  },
  {
    id: "mgo-100",
    slug: "mgo-100",
    name: "Manuka Honey MGO 100",
    mgo: 100,
    price: 18,
    size: "250g",
    potency: 2,
    tagline: "Active Immune Support",
    description: "A versatile honey for overall health support. MGO 100 offers moderate potency for consistent wellness routines.",
    benefits: ["Digestive Support", "Immunity Boost", "Health Maintenance"],
    bestFor: "Wellness",
    antibacterial: "Moderate",
    taste: "Mild-Med",
    image: "/honey-frames/ezgif-frame-004.jpg",
    imageLid: "/honey-frames/ezgif-frame-014.jpg",
    color: "#C49A2A",
  },
  {
    id: "mgo-263",
    slug: "mgo-263",
    name: "Manuka Honey MGO 263",
    mgo: 263,
    price: 40,
    size: "250g",
    potency: 3,
    tagline: "Natural Shield Protection",
    description: "High potency Manuka for targeted immunity. MGO 263 is ideal for those seeking stronger natural protection.",
    benefits: ["Strong Immunity", "Oral Health", "Gut Balance"],
    bestFor: "Immunity",
    antibacterial: "High",
    taste: "Medium",
    image: "/honey-frames/ezgif-frame-004.jpg",
    imageLid: "/honey-frames/ezgif-frame-014.jpg",
    color: "#D4930A",
  },
  {
    id: "mgo-400",
    slug: "mgo-400",
    name: "Manuka Honey MGO 400",
    mgo: 400,
    price: 70,
    size: "250g",
    potency: 4,
    tagline: "Therapeutic Grade Purity",
    description: "Therapeutic grade honey for intensive support. MGO 400 is widely used for digestive and wound care.",
    benefits: ["Wound Healing", "Intensive Gut Health", "Skin Care"],
    bestFor: "Gut/Wound",
    antibacterial: "Very High",
    taste: "Strong",
    image: "/honey-frames/ezgif-frame-004.jpg",
    imageLid: "/honey-frames/ezgif-frame-014.jpg",
    color: "#B87800",
  },
  {
    id: "mgo-800",
    slug: "mgo-800",
    name: "Manuka Honey MGO 800",
    mgo: 800,
    price: 160,
    size: "250g",
    potency: 5,
    tagline: "Clinical Grade Powerhouse",
    description: "Our most potent, clinical-grade Manuka. MGO 800 offers exceptional antibacterial activity for specialized health needs.",
    benefits: ["Clinical Support", "Max Antibacterial", "Premium Recovery"],
    bestFor: "Clinical",
    antibacterial: "Exceptional",
    taste: "Intense",
    image: "/honey-frames/ezgif-frame-004.jpg",
    imageLid: "/honey-frames/ezgif-frame-014.jpg",
    color: "#9B6500",
  },
];
